# 项目相关配置
ruoyi:
  # 名称
  name: 红叶网络验证与软件管理系统

server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

license:
  subject: ${ruoyi.name} #证书主题
  privateAlias: privateKey #公钥别称
  licensePath: D:/license.lic #license存储目录

