# 项目相关配置
app:
  version: 1.0.0
  download-url: https://cdbuju.oss-cn-hangzhou.aliyuncs.com/apk/cdbuju-1.0.0.apk
  update-notes: 正式上线
  forced-update: false
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证  num 纯数字
  captchaType: num
oss:
  endPoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tCrN19aDVWLLfpKVEZw
  accessKeySecret: aVddl48X8SoKua7NaI51CL1Am84XNp
  bucketName: cdbuju-pri
  publicBucketName: cdbuju
  https: true
  regionId: cn-hangzhou
  roleArn: acs:ram::1970150216435822:role/oss-upload
  expiredDuration: 3600
  tempDir: /temp/
  stsCacheDuration: 1800
  callbackUrl: https://api.cdbuju.cn/rest/v1/oss-callback/upload
img-search:
  endPoint: imagesearch-vpc.cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5t9e53VpzuR22AFtppMR
  accessKeySecret: 5pxzQtfGRK6q3CXmuFBy7KuL6T8zPs
  regionId: cn-hangzhou
  instanceName: buju0115
  # 如果是内网访问图像搜索服务，则endpointType为必填项，值统一为"internal"
  endpointType: internal
sms:
  accessKeyId: LTAI5tFmJ5DiJ1iq2hNe9PPB
  accessKeySecret: lCoSOQPkxgdQ6bDoi3TbAlsKXmOLp1
  regionId:
  send: true
  verificationCode:
    testModel: false
    signName: 成都智创步橘科技
    templateCode: SMS_323190329
ocr:
  accessKeyId: LTAI5tDTNoFKAUXJ996azKdS
  accessKeySecret: tbchxLXOioKcQW9PF9sgjPUZyMA3zm
  endpoint: ocr-api.cn-hangzhou.aliyuncs.com
es:
  #多个用","分割
  hosts: es-cn-em94bkrrl0005djma.elasticsearch.aliyuncs.com:9200
  ssl: false
  username: elastic
  password: 0tP&3!GZZDMrglBm&kWJyw
  maxConnTotal: 100
  maxConnPerRoute: 50
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为9310
  port: 9310
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: info
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: false
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://rm-bp17756y86qdc110z.mysql.rds.aliyuncs.com:3306/xiekutong?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: xkt
        password: mtd@3XKSoXm671Yc7oZ5G
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 100
      # 最小连接池数量
      minIdle: 100
      # 最大连接池数量
      maxActive: 200
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: r-bp1qhhpf6g2wcvvt71.redis.rds.aliyuncs.com
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: E5tVB*dSkc38UDP%F1#WjZ
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 50
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池的最大数据库连接数
        max-active: 200
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 3000

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置
  type-aliases-package: com.ruoyi.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  map-underscore-to-camel-case: true
  # 全局配置
  global-config:
    db-config:
      # 数据库配置
      id-type: auto


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 物流配置
express:
  default:
    province: 510000
    city: 510100
    county: 510114

# 中通配置
zto:
  appKey: 1907975e6c6eadc096284
  appSecret: f67e08e72825d857495105c7ed78bf14
  gatewayUrl: https://japi.zto.com/
  accountId: ZTO761752114633049
  accountPassword: AJXVWZMM

# 圆通配置
yto:
  appKey: K280280756
  appSecret: iplud2s6
  appKey2: ZCBJ_STD
  appSecret2: xJa1tc2A
  gatewayUrl: https://openapi.yto.net.cn:11443/

# 支付宝配置
alipay:
  appId: 2021005194684036
  appPrivateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCaD/WcIXsHs11Qgm9c32XbxZUZ/sTK4KxRLM6dvbZnLqxAgLKOf5zoEnuKIWP/PMvvymTfVPD1tWf5DC+xHRu4a/TLJawv2WZW4Y2FGUV5VTs0FRxnQqFB+5s2EdN/XS+FWCAaKjK86kdgzRNf3R4BCGaA2wUiIoYOv30PsrrDdzjrTk+9TXgXWVlldY1xEiEkB+J8C+PxyKdPJ2JCLKnPik+VmUZ/1fvGmVuTJj/4ofqCP3YmyBJSKQVi0IDQixLmawtawKf2FzGvLn6JQMRgzizFxtmYL2blbmwQ2Y93usIr2q1QRzbwNfxqzeu4h7DkRO7kPJPxjQiA91KL3dC/AgMBAAECggEAErWzd0Wdol7HC1r72USMIzeIlwKYtaa5ZpZRdVivyTIi2yaGCMY4sPplpG3PrhSdE775pyGyrbRdLyKqvBCz6B68ONuXYKw/QHfd7vcVt9mA+h9CNswht1iuDc/2ZnZTqhb8txC+3rB5AKmHG9JHrYpuoGF46x9UNoBM2NY01j349G63uqy0LEKiAqgDcWk2aH0jXG31q23aR4gOjirS47NApApPeAH7AKv1KQsWdzCSnWn0Tez7/qa+fi7J/O5mgxxcezLqkuSz3/pv+pQrj9+cOwqwrou9j82ZkESvCHY/7b5ewwu8YkdZLwJg/0/VG66cfk33QBgZ26aRHTBD+QKBgQDYAXS+d8sY2SfGyjBPfmgzxxqJTW173ybJFAjJQUQSj1ijdtoK/KL+Ql9smfs+hnKM9tHReIcgn+LDrEm1bEAxXAvRd1xlGHEP/H04V3liznvxvTa/u7oZIdkU+6R+P7urVM7cYoqCnsVs4jRI2GdrSAStQOezEyVeOAFFEBMkhQKBgQC2lmy/o/7jFnnvVBbCtfKX6R26p847gxBU3+ve9HLVYFq0JuLjDIdTgRuLCX/vx1MKabu/o4BX9cv+VHqhdTLfLRDagGAehpHgD1Ey/dPrwBYUOL+V0R9jVEFxRO6VmsP9Zdk0XnV6QpaQjSZCvqXfBSZLMZT3D4JlTKV8v+eVcwKBgQCmMbiZM6JYI/yuvrIc961E6VRJgAFU5YT6ASghcM3nWdNhMfjhqy/dYUP6Ux80JE3Ol7kn6gxN1barxsuPgxKA58lQCP5V6lBTdHkD+Im0tBo5DNQrAU1WOOzFcDhHytGiKUZf2pGnnnFYLVL9GUO5D1hJ1T5wUbLWo1CWyp9v4QKBgARmLWqUnfCEux1cDkxUq+qjEDdOEbb3Wm5hEsLFavrfHnBWu4Ky65PEeZBpAy8Yw1Rt5bshSldUMb0H9ghr1XTxFgXdr/MsVNlsJQ2wdempMB7+mwcWCcaP4h/DhGgQWYaCbLBJUlVGw2/qJrDW/RIZgqmvISKuufqM1TPjP8YnAoGBAKQF9JYZgNjJW3jVuwecPhvH6rrQLDGKRTLjZphO2mFljzjxy/nGcqdyrgplNk4MiKSGsNZPPS8L88epktEbow1YrrF0ESEVq4WYCHW1kMHs2ab8vieehjDbBYcIHtXywjphLNHNkfICIIWBoCrrR+gd1noEjOuEllcnbPHuDREn
  appCertPath: /alipay/prod/appCertPublicKey_2021005194684036.crt
  rootCertPath: /alipay/prod/alipayRootCert.crt
  alipayPublicCertPath: /alipay/prod/alipayCertPublicKey_RSA2.crt
  notifyUrl: https://api.cdbuju.cn/rest/v1/alipay-callback/notify
  defaultReturnUrl: https://cdbuju.cn/index.html
  orderReturnUrl: https://cdbuju.cn/index.html
  signType: RSA2
  charset: UTF-8
  gatewayUrl: https://openapi.alipay.com/gateway.do

# 阿里认证
aliauth:
  captcha:
    appId: 386ec134856c9fe7d47ce2a34ee91038
    appKey: 1b4e3ff703ca1ea0fb802d188079a25c

# 腾讯认证
tencent:
  secretId: AKIDEbxNfmkW5RaVDhDc2Pcs198zpeP6kEZi
  secretKey: 3ub7QZYN9qR4bxBE6qQs9GBuSnuoW0JP
  captcha:
    captchaAppId: 199022475
    appSecretKey: wcqMdqjV3fnvFKxUAq5mwulnD
