# 项目相关配置
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: D:/ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证  num 纯数字
  captchaType: num
oss:
  endPoint: oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tCrN19aDVWLLfpKVEZw
  accessKeySecret: aVddl48X8SoKua7NaI51CL1Am84XNp
  bucketName: cdbuju-pri
  publicBucketName: cdbuju
  https: true
  regionId: cn-hangzhou
  roleArn: acs:ram::1970150216435822:role/oss-upload
  expiredDuration: 3600
  tempDir: E:/temp/
  stsCacheDuration: 1800
img-search:
  endPoint: imagesearch.cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tMbgwJxYgKwc2fCC1oT
  accessKeySecret: GQbasTQ3QVu92sCbnVJMFfaGybIosx
  regionId: cn-hangzhou
  instanceName: zengsanmeiliuboboer
  # 如果是内网访问图像搜索服务，则endpointType为必填项，值统一为"internal"
  endpointType:
sms:
  accessKeyId: LTAI5tFmJ5DiJ1iq2hNe9PPB
  accessKeySecret: lCoSOQPkxgdQ6bDoi3TbAlsKXmOLp1
  regionId:
  send: true
  verificationCode:
    testModel: false
    signName: 成都智创步橘科技
    templateCode: SMS_323190329
ocr:
  accessKeyId: LTAI5tDTNoFKAUXJ996azKdS
  accessKeySecret: tbchxLXOioKcQW9PF9sgjPUZyMA3zm
  endpoint: ocr-api.cn-hangzhou.aliyuncs.com
es:
  #多个用","分割
  hosts: es-cn-em94bkrrl0005djma.public.elasticsearch.aliyuncs.com:9200
  ssl: false
  username: elastic
  password: 0tP&3!GZZDMrglBm&kWJyw
  maxConnTotal: 4
  maxConnPerRoute: 2
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为9310
  port: 9310
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # redis 配置
  redis:
    # 地址
    host: r-bp1qhhpf6g2wcvvt71pd.redis.rds.aliyuncs.com
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: E5tVB*dSkc38UDP%F1#WjZ
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 3000

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置
  type-aliases-package: com.ruoyi.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  map-underscore-to-camel-case: true
  # 全局配置
  global-config:
    db-config:
      # 数据库配置
      id-type: auto


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 物流配置
express:
  default:
    province: 510000
    city: 510100
    county: 510114

# 中通配置
zto:
  appKey: 95dc4ecf72fce1a2fbe79
  appSecret: 694ea7e3ea89e3b6aa21aea1a0285d25
  gatewayUrl: https://japi-test.zto.com/
  accountId: test
  accountPassword: ZTO123

# 圆通配置
yto:
  appKey: K9991024989
  appSecret: u2Z1F7Fh
  appKey2: TEST
  appSecret2: 123456
  gatewayUrl: https://openuat.yto56test.com:6443/

# 支付宝配置
alipay:
  appId: 9021000144616672
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCLx2n7L1HNr8Tq92TUNJ/q66hWWHvoAwDxP27mpOrVbBwMCquxOW8ajMXooO6S/+d5PCZ1CXEjT2JpA264ptuY3LWnVbBWg6gxFzq2dX8XKk10GxdYQ63H3ZGHdPSgvUnHrG7AWSckbPSyutWXkeZITQJiD0Md/YxtjwxlW490EwTWRGLPgjoooJ9CdDgmvMgwJzUqV03rHLAPRVW1MhEBg4dJ2XtSMY0UzVejb+esOyrshNHTPoTQNUIONjPMEiihX7/ujRxUif8c/AYQh8sF3igVXSojghkJAhGboZbdBXf5VRx4DURgR0O1oujE1eG+qxYYk00Z5wa14+FPlP7RAgMBAAECggEAKru4hvach8mo5jzkMow0J9oMCPncR75DV34RJapdsQnwOS4592Cbuv42szwgNAjQd5wQFc/hKu5mI7zM6N76W+1+C76CvrBZh0iWxpl9VVO1gj2WEYH/aw8uIr962nmESOtKoLug393/oXTFQCV2xbvlcp0/47dUa1pEa+hmHxINZ7CJGQKiCjL9826lvpOyXigHaTYDu/fZluviu73lPIFyE62ZvEPfEPhpdt41pP/7ooCqarPMvqHb+7joKFSHDLJwjqdmZreh0vy5r9Dl2v79q1sbZ/30DWxa4Beb/y6SJT5lC2T7s+JZFIJ8igHXPsd7tY46Ko2AJmAg/JdvwQKBgQDNPniD8ssGdJ/M4jRrjqMwqpixBZvkgQwyl2HNp9LKRGDTuxT+4oDe9Y8e1a/jzYx64MJWOr0syR3HNggb09/mLpba8SBWqUqHCdU20hLbkAhs9kC18eBTAyKP1lDJgGKIM9AckYnJl0wwk6uD8r960kwkPjPNhLniuUMPMaDJbQKBgQCuWH/3EU8of/ZKpzsH90u3fdwhFJBQzlf4ZhWYnbFyDDdrEnobGlG642b5l6F/QTKj8+NvitTCWjYPZSz4hbSk3eNaN71bIf84KAWu1ab/+DNaMNXwzoQhXGTK86OLf8QWt93l90BIvUA2KACunUM1L/OwN5G9uFfH/nbrnFawdQKBgCfVGvCIu0xKcAUEVaYWLaexRCb+7q1fOi3LYWjXTDqDIMOWyFFbRiV/RMJ4OEWey8fBPRYdGj/J3GSgINy9tvNmUVK2f08yVct1ZhLYnF5OSsRS2mY1RhL2RcvijRU+PGEwpRAWUsZz/Y5j6mKWRwEgNTTHeahGPQk6aUBWolzVAoGAMml4pvIkV2uYxcFROl5xUF9eNVqC2DqyCStLd1OxqW6K37T6Bbg4hbeXYPhNRESP5gRxcSFNn90B4LW6qSnQMBPQ15dic2WDLLO14PX6Ue1su9l/IyAz6ImUw3Jribyp8H+98+7ocZ/3XzF18QecFVcGOZ/3zkntZ/DWZg5QqrkCgYBELNA1N1td+MA0VrncUF8c5kH7XI6KGfYqZR6QW4ouQa2Xu5WhfWAv68GsEBUmTIFDZQHNOKMC6qNq4BrGZ+C0S3A8FZIBvo3ztKxG1MQvznuh28vjN/yQu0qAx55JPXvJJVSPfvGXIk4lvhw53ZwYTvHjyR517AiQKemdESKQKw==
  appCertPath: C:/alipay/test/appPublicCert.crt
  rootCertPath: C:/alipay/test/alipayRootCert.crt
  alipayPublicCertPath: C:/alipay/test/alipayPublicCert.crt
  notifyUrl: http://101.34.251.164:9310/rest/v1/alipay-callback/notify
  returnUrl:
  signType: RSA2
  charset: UTF-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 阿里认证
aliauth:
  captcha:
    appId: 386ec134856c9fe7d47ce2a34ee91038
    appKey: 1b4e3ff703ca1ea0fb802d188079a25c
