# 项目相关配置
app:
  version: 1.0.0
  download-url: http://oss.cdbuju.cn/apk/cdbuju-1.0.0.apk
  update-notes: 正式上线
  forced-update: false
ruoyi:
  # 名称
  name: RuoYi
  # 版本
  version: 3.8.9
  # 版权年份
  copyrightYear: 2025
  # 文件路径 示例（ Windows配置D:/ruoyi/uploadPath，Linux配置 /home/ruoyi/uploadPath）
  profile: /ruoyi/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数字计算 char 字符验证  num 纯数字
  captchaType: num
oss:
  endPoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI5tFXTfY5Rsiwvrg9gUuk
  accessKeySecret: Ebbj7anXSdbJwfm5zbTfHkJ5QWDbTP
  bucketName: lyq-private
  publicBucketName: lyq-public
  https: true
  regionId: cn-beijing
  roleArn: acs:ram::1919425406190533:role/sts-role
  expiredDuration: 3600
  tempDir: /temp/
  stsCacheDuration: 1800
  callbackUrl: http://112.124.31.119:9310/rest/v1/oss-callback/upload
img-search:
  endPoint: imagesearch.cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI5tBFXhTu7Di1ZumRPYZs
  accessKeySecret: HJqVUr8UoFRzYDAiBf2pn55rE2TLbu
  regionId: cn-hangzhou
  instanceName: search20250826
  # 如果是内网访问图像搜索服务，则endpointType为必填项，值统一为"internal"
  endpointType:
sms:
  accessKeyId: LTAI5tFmJ5DiJ1iq2hNe9PPB
  accessKeySecret: lCoSOQPkxgdQ6bDoi3TbAlsKXmOLp1
  regionId:
  send: true
  verificationCode:
    testModel: true
    signName: 成都智创步橘科技
    templateCode: SMS_323190329
ocr:
  accessKeyId: LTAI5tDTNoFKAUXJ996azKdS
  accessKeySecret: tbchxLXOioKcQW9PF9sgjPUZyMA3zm
  endpoint: ocr-api.cn-hangzhou.aliyuncs.com
es:
  #多个用","分割
  hosts: 47.99.90.75:9200
  ssl: false
  username: elastic
  password: wXd3iRUcqHzxZPtKsDRn
  maxConnTotal: 4
  maxConnPerRoute: 2
  indexName: dev_product_info
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为9310
  port: 9310
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码最大错误次数
    maxRetryCount: 5
    # 密码锁定时间（默认10分钟）
    lockTime: 30

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/cdbuju?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: xvV@1WaZbkjSJjRO
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: false
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: ruoyi
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password: PamdI7H1owqQmYfA
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 3000

# MyBatis配置
#mybatis:
#  # 搜索指定包别名
#  typeAliasesPackage: com.ruoyi.**.domain
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath*:mapper/**/*Mapper.xml
#  # 加载全局的配置文件
#  configLocation: classpath:mybatis/mybatis-config.xml

# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置
  type-aliases-package: com.ruoyi.**.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  map-underscore-to-camel-case: true
  # 全局配置
  global-config:
    db-config:
      # 数据库配置
      id-type: auto


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 物流配置
express:
  default:
    province: 510000
    city: 510100
    county: 510114

# 中通配置
zto:
  appKey: 95dc4ecf72fce1a2fbe79
  appSecret: 694ea7e3ea89e3b6aa21aea1a0285d25
  gatewayUrl: https://japi-test.zto.com/
  accountId: test
  accountPassword: ZTO123

# 圆通配置
yto:
  appKey: K9991024989
  appSecret: u2Z1F7Fh
  appKey2: TEST
  appSecret2: 123456
  gatewayUrl: https://openuat.yto56test.com:6443/

# 支付宝配置
alipay:
  appId: 9021000144616672
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCLx2n7L1HNr8Tq92TUNJ/q66hWWHvoAwDxP27mpOrVbBwMCquxOW8ajMXooO6S/+d5PCZ1CXEjT2JpA264ptuY3LWnVbBWg6gxFzq2dX8XKk10GxdYQ63H3ZGHdPSgvUnHrG7AWSckbPSyutWXkeZITQJiD0Md/YxtjwxlW490EwTWRGLPgjoooJ9CdDgmvMgwJzUqV03rHLAPRVW1MhEBg4dJ2XtSMY0UzVejb+esOyrshNHTPoTQNUIONjPMEiihX7/ujRxUif8c/AYQh8sF3igVXSojghkJAhGboZbdBXf5VRx4DURgR0O1oujE1eG+qxYYk00Z5wa14+FPlP7RAgMBAAECggEAKru4hvach8mo5jzkMow0J9oMCPncR75DV34RJapdsQnwOS4592Cbuv42szwgNAjQd5wQFc/hKu5mI7zM6N76W+1+C76CvrBZh0iWxpl9VVO1gj2WEYH/aw8uIr962nmESOtKoLug393/oXTFQCV2xbvlcp0/47dUa1pEa+hmHxINZ7CJGQKiCjL9826lvpOyXigHaTYDu/fZluviu73lPIFyE62ZvEPfEPhpdt41pP/7ooCqarPMvqHb+7joKFSHDLJwjqdmZreh0vy5r9Dl2v79q1sbZ/30DWxa4Beb/y6SJT5lC2T7s+JZFIJ8igHXPsd7tY46Ko2AJmAg/JdvwQKBgQDNPniD8ssGdJ/M4jRrjqMwqpixBZvkgQwyl2HNp9LKRGDTuxT+4oDe9Y8e1a/jzYx64MJWOr0syR3HNggb09/mLpba8SBWqUqHCdU20hLbkAhs9kC18eBTAyKP1lDJgGKIM9AckYnJl0wwk6uD8r960kwkPjPNhLniuUMPMaDJbQKBgQCuWH/3EU8of/ZKpzsH90u3fdwhFJBQzlf4ZhWYnbFyDDdrEnobGlG642b5l6F/QTKj8+NvitTCWjYPZSz4hbSk3eNaN71bIf84KAWu1ab/+DNaMNXwzoQhXGTK86OLf8QWt93l90BIvUA2KACunUM1L/OwN5G9uFfH/nbrnFawdQKBgCfVGvCIu0xKcAUEVaYWLaexRCb+7q1fOi3LYWjXTDqDIMOWyFFbRiV/RMJ4OEWey8fBPRYdGj/J3GSgINy9tvNmUVK2f08yVct1ZhLYnF5OSsRS2mY1RhL2RcvijRU+PGEwpRAWUsZz/Y5j6mKWRwEgNTTHeahGPQk6aUBWolzVAoGAMml4pvIkV2uYxcFROl5xUF9eNVqC2DqyCStLd1OxqW6K37T6Bbg4hbeXYPhNRESP5gRxcSFNn90B4LW6qSnQMBPQ15dic2WDLLO14PX6Ue1su9l/IyAz6ImUw3Jribyp8H+98+7ocZ/3XzF18QecFVcGOZ/3zkntZ/DWZg5QqrkCgYBELNA1N1td+MA0VrncUF8c5kH7XI6KGfYqZR6QW4ouQa2Xu5WhfWAv68GsEBUmTIFDZQHNOKMC6qNq4BrGZ+C0S3A8FZIBvo3ztKxG1MQvznuh28vjN/yQu0qAx55JPXvJJVSPfvGXIk4lvhw53ZwYTvHjyR517AiQKemdESKQKw==
  appCertPath: /alipay/test/appPublicCert.crt
  rootCertPath: /alipay/test/alipayRootCert.crt
  alipayPublicCertPath: /alipay/test/alipayPublicCert.crt
  notifyUrl: http://112.124.31.119:9310/rest/v1/alipay-callback/notify
  defaultReturnUrl: http://116.62.108.187/index.html
  orderReturnUrl: http://116.62.108.187/index.html
  signType: RSA2
  charset: UTF-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

# 阿里认证
aliauth:
  captcha:
    appId: 386ec134856c9fe7d47ce2a34ee91038
    appKey: 1b4e3ff703ca1ea0fb802d188079a25c

# 腾讯认证
tencent:
  secretId: AKIDEbxNfmkW5RaVDhDc2Pcs198zpeP6kEZi
  secretKey: 3ub7QZYN9qR4bxBE6qQs9GBuSnuoW0JP
  captcha:
    captchaAppId: 199022475
    appSecretKey: wcqMdqjV3fnvFKxUAq5mwulnD

# 飞书
fs:
  robot:
    monitorSwitch: true
    monitorChartId: oc_34e207df88addd15d83ec274fda95ef6
    monitorEnv: 测试