spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_modules?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver


